nelmio_cors:
    defaults:
        allow_origin: []
        allow_methods: []
        allow_headers: []
        max_age: 0
    paths:
        '^/api/':
            allow_credentials: true
            allow_origin: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600
