services:
  _defaults:
    public: true

  doctrine.orm.default_entity_manager:
    lazy: true

  App\Infrastructure\Persistence\Doctrine\Repository\AttributeValueRepository:
    arguments: [ '@doctrine.orm.entity_manager' ]
    public: true

  App\Infrastructure\Queue\Amqp\ChannelInterface:
    class: App\Infrastructure\Queue\Amqp\NullChannel
    public: true

  App\Application\Shared\Contract\TransactionServiceInterface: '@App\Infrastructure\Test\Stub\TransactionalServiceStub'

