---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include ".helm.fullname" . }}-configmap
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;

    error_log /var/log/nginx/error.log notice;
    pid /var/run/nginx.pid;


    events {
      worker_connections  1024;
    }

    http {
      include /etc/nginx/mime.types;
      default_type application/octet-stream;

      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
        '$status $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"';

      access_log /var/log/nginx/access.log main;
      error_log /var/log/nginx/error.log debug;

      sendfile on;
      keepalive_timeout 65;

      server {
        listen 80;
        server_name _;

        access_log /var/log/nginx/access.log main;
        error_log /var/log/nginx/error.log debug;

        location ~* /favicon\.ico$ {
          root /app/public;
          try_files /favicon.ico =404;
        }

        location / {
          fastcgi_pass 127.0.0.1:9000;
          fastcgi_split_path_info ^(.+\.php)(/.*)$;
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME /app/public/index.php;
          fastcgi_param DOCUMENT_ROOT $realpath_root;
        }

        location ~ \.php$ {
          return 404;
        }
      }
    }
