---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include ".helm.fullname" . }}-resource-volume
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
