image:
  sidecar:
    repository: nginx
    pullPolicy: Always
    tag: 1.23-alpine-slim

  app:
    repository: vasary/tac-core
    pullPolicy: Always
    tag: latest

nameOverride: "inventory"
fullnameOverride: "inventory"

ingress:
  domain: inventory.tac.com

service:
  type: ClusterIP
  port: 80

environment:
  secret:
    name: inventory
  variables:
    APP_SECRET: app_secret
    MQ_HOST: amqp_host
    MQ_PORT: amqp_port
    MQ_USER: amqp_user
    MQ_PASSWORD: amqp_password
    MQ_VHOST: amqp_vhost
    SSO_DOMAIN: sso_domain
    SSO_CLIENT_ID: sso_client_id
    SSO_SECRET: sso_secret
    SSO_COOKIE_SECRET: sso_cookie_secret
    SSO_AUDIENCE: sso_cookie_audience

resources:
  sidecar: {}
  app: {}

securityContext:
  sidecar: {}
  app: {}

nodeSelector: {}
tolerations: []
affinity: {}
podAnnotations: {}
podSecurityContext: {}
