name: Tests
on:
  push:
    branches:
      - master
jobs:
  security:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: PHP Security Checker
        uses: StephaneBour/actions-php-security-checker@1.2
        with:
          composer-lock: './composer.lock'
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.1', '8.2']
    name: PHP ${{ matrix.php-versions }}
    steps:
      - name: Setup PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: uopz redis pdo pdo_sqlite sockets intl
          coverage: xdebug

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies (PHP vendors)
        run: composer install -q --no-ansi --no-interaction --no-suggest --no-progress --prefer-dist

      - name: Execute tests via PHPUnit
        run: bin/phpunit

      - name: Coverage Report as Comment (Clover)
        uses: lucassabreu/comment-coverage-clover@main
        with:
          file: resource/coverage.xml
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    name: Build application container
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build unit sources
        run: git clone https://github.com/nginx/unit

      - name: Build unit container
        run: cd pkg/docker && make build-php82 VERSION_php=8.2.1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: vasary/tac-core:latest
