name: Delete old workflow runs
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: vasary/tac-core
          retain_days: 0
          keep_minimum_runs: 1
