name: Checks and tests
on:
  push:
    branches:
      - feature/*
      - renovate/*
jobs:
  security:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate composer.lock
        uses: composer validate --no-check-all --no-check-publish

      - name: PHP Security Checker
        uses: StephaneBour/actions-php-security-checker@1.2
        with:
          composer-lock: './composer.lock'
  tests:
    needs: [security]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    name: PHP 8.2
    steps:
      - name: Setup PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: uopz redis pdo pdo_sqlite sockets intl
          coverage: xdebug

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies (PHP vendors)
        run: composer install -q --no-ansi --no-interaction --no-suggest --no-progress --prefer-dist

      - name: Execute tests via PHPUnit
        run: bin/phpunit

      - name: Coverage Report as Comment (Clover)
        uses: lucassabreu/comment-coverage-clover@main
        with:
          file: resource/coverage.xml
