name: Checks and tests
on:
  push:
    branches:
      - feature/*
      - renovate/*
jobs:
  artifact:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/upload-artifact@master
        with:
          name: source
          path: .

  validate:
    needs: [artifact]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/download-artifact@master
        with:
          name: source
          path: .

      - name: Validate composer.lock
        run: composer validate --no-check-all --no-check-publish
  security:
    needs: [artifact]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/download-artifact@master
        with:
          name: source
          path: .

      - name: Test
        run: ls -lah

      - name: Validate composer.lock
        run: composer validate --no-check-all --no-check-publish

      - name: PHP Security Checker
        uses: StephaneBour/actions-php-security-checker@1.2
        with:
          composer-lock: './composer.lock'
  tests:
    needs: [validate, security]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.1'
          extensions: uopz redis pdo pdo_sqlite sockets intl
          coverage: xdebug

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies (PHP vendors)
        run: composer install --no-ansi --no-interaction --no-suggest --no-progress --prefer-dist

      - name: Execute tests via PHPUnit
        run: bin/phpunit

      - name: Coverage Report as Comment (Clover)
        uses: lucassabreu/comment-coverage-clover@main
        with:
          file: resource/coverage.xml
