name: Renovate
on:
  schedule:
    - cron: '0/5 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install project
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build

      - name: Renovate
        uses: renovatebot/github-action@v34.82.0
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
